name: face-beauty-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - dlib
  - opencv
  - numpy
  - pandas
  - scikit-learn
  - scipy
  - plotly
  - pillow
  - pip
  - pip:
      - streamlit
      - imutils
